debug: true
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Niclas123
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop # none, create ...
  sql:
    init:
      platform: postgresql
      mode: always
    output:
      ansi:
        enabled: always
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

auth0:
  audience: http://localhost:8080
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-bsoabtbd2ae2u6vw.us.auth0.com/