debug: true
server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: Sh6DVjDkmQI8ryNrkmEG5eecFWFJIbIc
            client-secret: RJco3dSHnE2H2XOzQ9UnbmYdyxR_LRNWaO2JJummN-BogIh7yL3aIrhXhvghYSCz
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-bsoabtbd2ae2u6vw.us.auth0.com/
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Niclas123
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop # none, create ...
  sql:
    init:
      platform: postgresql
      mode: always
    output:
      ansi:
        enabled: always
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
auth0:
  audience: https://dev-bsoabtbd2ae2u6vw.us.auth0.com/api/v2/
